### PR TITLE
Chris exploration

### PR DESCRIPTION
**Pull request by CShine612**
Dummy model features extracted and modeled using LinearSVC

### CODE REVIEW

**Comment by NahiaPeschard** [comment]
Great job!!

2 remarks:
1. Name 'string' is not defined: am I missing something?
2. If would be great if the first 5 extracted features could have a meaningful name: what do you think?

**Comment by CShine612** [comment]
Comments address and notebook cleaned

**Comment by palaiole13** [comment]
Nice work!

Just added one more feature, based on Daniel's suggestion (appearance of semicolon and dash, as indicative of more academic/scientific papers). Seems similar to punctuation, but might be getting smth more, as academic titles won't use ! as much for example. Tried it and raises baseline to 10.7

Code:

count_special_chars = lambda s: sum(1 for c in s if c == ':' or c == '-')
special_chars_count = X['Title'].apply(count_special_chars)
special_chars_ratio = np.array(special_chars_count/count_words)
extracted_features['special_chars_ratio'] = special_chars_ratio

# inside pipeline:
class TitleFeatureExtractor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.count_words = lambda s: len(s.split())
        self.count_capital_letters = lambda s: sum(1 for c in s if c.isupper())
        self.count_letters = lambda s: sum(1 for c in s if c.isalpha())
        self.count_punctuation = lambda s: sum(1 for c in s if c in string.punctuation)
        self.count_special_chars = lambda s: sum(1 for c in s if c == ':' or c == '-')
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        extracted_features = pd.DataFrame()
        extracted_features['count_words'] = X['Title'].apply(self.count_words)
        extracted_features['capital_ratio'] = X['Title'].apply(lambda s: self.count_capital_letters(s) / self.count_words(s))
        extracted_features['letter_ratio'] = X['Title'].apply(lambda s: self.count_letters(s) / self.count_words(s))
        extracted_features['punct_counts'] = X['Title'].apply(self.count_punctuation)
        extracted_features['special_chars_ratio'] = X['Title'].apply(lambda s: self.count_special_chars(s) / self.count_words(s))
        
        return extracted_features.values

**Comment by palaiole13** [comment]
Sorry for non-uniform format in the comment

**Pull request merged**
